---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets
  namespace: discord-bot
spec:
  encryptedData:
    sentryDsn: AgBQl96c35VkqV3LcbrSVFMAiRlpP8SrLdVNz9QWvmNA2op3ASxEcgmKgqZB3QESaGObYhL1BuUnWBZdQUXY/Pi+BgkYDomJYSfQk428bri8HU+DzX1IwuB5MdE3J1i4iEOtintcufNuuxDI/Q8989hSDy1X4x5YRDbaJDR7FN80ptBWmWSgO699xzFyJ1fUUcbhOJblwzmEXIk1tZ8KTkWQuXTMmV0yFmS814TBxIJhAoVqNA1Zs8Srmw0NYscrvCPDR/OTkCsVfPG6rX7sgJUukjk/6u+wKfK4wYtHZSlLl5ztEgmm0nU9EnPzqHgvHGyFzndkOBJLYOjgNsR59rXQwpNNBDuBMdjlHp4FCJrC7JUqkEZHJox9w0EapMh70HZ99w8qjptbu8w4MLn14vvjqTAzOc/6dM1x11NZKz5Gr8z4kE1LozhfGJKOFNr05wbaKn3RK6ZycSnLoUWvUhh7JNKM9NbYG7vyHH/mvIdPfAJ0mBEkjqo2p8YcwAzjdG/FlIRo3g/9Wgpwd9J9X2bHk6uNKhfk57TKTVm13szVI+fILHqUxqe0WYojkmanLlhmreJhWvYCgdx6BYE901TFK4yCg734iXPhuzDYKiPnzww85VMZm8uF9WH9hZN/K5w2An//c9MVyoydUiecdU1H02uKPL6ddH44YRT74FAMyaukeMixaqnVHg6Nv6r36VoLBlu1EY31XGXRi/J6Cn97OoQ33BQZGboL1UzwNSLM2gqCCduBn0psHcetFQqWDZlsQLU2V83HJQKI3CN5sIBSSdkyJroJeQ4yaHBNxAe/b9VXcEarzPTNTLk8QEuVag==
    token: AgB8S067TncTMHK2qVBqQcRp0RLGvY4FFDyan9kS9Cm+bzH0F0T4kzt/+Q0V1rMQEwRiEwWUE3K4H2CXGGA9EuaDpq19AgyQ2/26EtA3ct37rIJRtNQiuQw73mSEMpEJf0tZa48dhHBFK9cmwr4pf/fQ2GnfuwM2hTuJb/LiW7nuSuplTwcfomlKuL+vNkD5iLc/ZYmNNXLKtNp8JLhZSQcZgwMGne3Rd9E6rnK8xZqf/QIsmZFqslB/bM4LBAd/vdIERgl/AYRVzXpqcNqeZInpmyhRbnBWYGH88wnEelKvGdlwb3i7kjJRuD0XqHFDu6Qipt6iRGUifT/M3MLDHb5IwKwHP6xIPxE7aXqkiYYDn185q4z+RssHiHJIs8XXw4L4/vp9WQ6Cc4E1h5yp8RJvbn+eVNiv1gXXJR7U7EL9b7qVyKfjxOeZs/f574RJmso+GJ9UD3zIXn3MyZZG0glQi5pTUWGgxr+TeHHzYh0ZfDBBIlV/nCQJdIcrY5eVv3tASMnrRJKbHTgB4EO/0gjidJpHj+WwZM8rPwWhFKFG5PCQ6ju4BJvYwXQnAfVo7XtlAlYkx8XrmjUjzDIWDmWrb+FHWA5MXuyUfpqqScZW43zFNLzyCi98DjuXNwiOIbrhIhomcP1kIUWgUZGGm2hOEN6A8AfmLPu8de/WWrK7Ptlcm9L7A4QIHJkqlCfwy1rrHy+7C9LdBU2dF6qLNp5GVKc27xA5KcVXFQW9c1X0F17uSIhahhw4sTKX80Gau6SiDLSfIxGjeXHxyBxMZesE4NYpF7tR
  template:
    metadata:
      creationTimestamp: null
      name: secrets
      namespace: discord-bot
