---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBQh5IjUzj7opAOSj8Efwps6TqFxPOHKbQLeF5LBq4JWbg3+R4UN2Wwy13Wv0LURRIA01awlpeiKZftRaogxw9mNWUIMhKKY4SXYu8r+XUuDWhbLyCiaYkYr9hgqvk3r3IlxICyK+xd5RGS1x+yp5PvOKw4Fur9YLOK2+teKjQW2G/dP0xif8WVeUB+cG08Z3b7F2F4knbstfcqO0D+H8Mh/RHbh/wIMAGnxP6WatEMEo/FxsIrnbwMKrCeL3x9swhKrWbQdaCVMxOr/hND+Csv1y+4L2BbQPYsbbYIHySVPgHaLyfvS7EJqj4iL59yP9+BlE9Q5ToIZ6QMVdIfkva2m0qIXpSL4kmcRUhHxrf5L91AunrlPCczizhn1P/gnrkQ9poTLLjW9tWsn55lyV8D4pY9EFIYy1MZzzTRTDkQ77JVqNtG0pg0hvayltKpuuQzvKTkwT1CpDT7WM6YKhZf+w6xAjC+jvDaghtJ2O9iMNC2WaTu0XEBFCLMR+X+JRMn1o77rTxNoOuEv2IDjW+JbHtTyuDMYGXRAla9Cgc7SAoS8BYoBydgzGol9fbVeAPvUI/eZ2uMvXxV8aiVl+yAcLXPo3ILHNzTS2WMEibuG+qBTlTtElbjJj37+wXhtjVo+p7SRGs1dkb9hc0J8XSjsN5pQ1FkzwaqoEPfesB7crIsnnj6YoOLlzdTsmJpyP9lc3Oqf9lZ1ygCprYsSBxcVg==
    client_secret: AgA0fKf5UorTZoB+qJtmpVoiCg9YNvlS2hQqJ8mP1VblIUSSsFD8twv4dIjKYQLzZaxJk9WBrkgIhrCA1YCcLNO3YuAVZXmx1MacmPo0MBVevIPJyzd8hZBoLN/87CDLjh0pWf8bQzjoY640WVv/6AoVqGaSkhgVGI8+XA7fC+NHYEev4Bqg59WZSIEyge8CzulgLkCS5jekEI4BwULsCHSsOfGr5fo8IG06HSZj1/opw5wqsWCauo687uGgEWWGUdMcMEIfFZ8wsTnrroYREa3gqsFUnMjlJIY0xVbw64jIPGqRoKaxCXMOLPUnDlEx+w8xiYZQDIGv/gSkq1jMNQjxFnvbZ5m8VGPP0rbNU8U4MGbhDh4WHe+FdxQOOJDya8cuAdocs46YGiXfF+CO2tWnh0Dx7Pkd9lAIo3oq4LbHlky/XSHS3kRGu+ujHp3ql5uBp38QGyNcqtKb3XKWUVb+cDA7cDkYh2VuwG7AnQObcgL3cBBWQ2qMNBfsQuivANysZE7R9uQf7VgdnNsD7JtkjlIUCsXss7eODoxZEaIKp2Z6+rzb+Uw3HJN4xb21RM2KZ4/bEb9gziiie5gniSj6/e+Z8hFTaz6lcFFKhy/UKZwd3i5SA5divXlyWxOVsm3vTro+Z2SDXfghFSw1wvo6TuHgGrwlLBx1+M67M7anO34FTUwLgZgQveb0UbcsxaA9NYZVKuJHOF1iDT3Mt8rXcKQFIZf1hi5Ztkq2mne7NdcQydfsKz9TutcvOAmCidtvVkoGvJ/jn6u96chLU5ej
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
